
# Common stuff for most (if not every) smart devices
# Expected substs: device_name, comment

esphome:
  name: "${device_name}"
  comment: "${comment}"

# Enable Home Assistant API
api:
  password: !secret api_password

# For auto-discovery
mdns:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

captive_portal:
