esphome:
  name: "flash_me"
  comment: "Dummy device"

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "device fallback"
    password: "12345678"

captive_portal:


bk72xx:
  board: generic-bk7231n-qfn32-tuya

