
# Put your WiFi network name here
wifi_ssid: "your_wi-fi_network_name"

# Put your WiFi password here
wifi_password: "your_wi-fi_password"

# Put your backup password here.
# If device is unable to connect to your WiFi, it will start its own WiFi network. This is the password for that network.
ap_password: "backup_ap_password"

# EspHome API password as configured in Home Assistant. Leave blank if not sure.
api_password: ""

# Password for Over-The-Air updates. You will lose the OTA if this password doesn't match! Leave blank if not sure.
ota_password: ""
